#!/usr/bin/python
# Nombre : pygame5.py
import pygame
import sys

from pygame.locals import *

ancho,largo = 500,400

clock = pygame.time.Clock
class Pelotas (pygame.sprite.Sprite):
    def __init__(self,img):
        pygame.sprite.Sprite.__init__(self)
        self.image = pygame.image.load(img)
        self.rect = self.image.get_rect()
        self.rect.move_ip(0,0)
        self.rectAnt = self.rect
        self.t=0

    def update(self):
        keys = pygame.key.get_pressed()
        if keys[K_RIGHT] and self.rect.x < ancho-30:
            self.rect.x += 2
        if keys[K_LEFT] and self.rect.x > 10 :
            self.rect.x -= 2
        if keys[K_UP] and self.rect.y > 10:
            self.rect.y -= 2
        if keys[K_DOWN] and self.rect.y < largo-30:
            self.rect.y += 2

        screen.blit(self.image,self.rect)
        c = len(pygame.sprite.spritecollide(self,g,False,None))
        if c >= 2:
            print ("Perdiste: Uff chocaste",c)
            sys.exit(0)

        if self.rect.x == ancho - 30 and self.rect.y == largo-30:
            print ("Wiiii GANASTE")
            sys.exit(0)
        else:
            self.t+=1

        self.rectAnt = self.rect

class Elementos (pygame.sprite.Sprite):
    def __init__(self,img,x,y,p):
        pygame.sprite.Sprite.__init__(self)
        self.image = pygame.image.load(img)
        self.rect = self.image.get_rect()
        self.rect.move_ip(x,y)
        self.direccion = p
    def update(self):
        keys = pygame.key.get_pressed()
        self.rect.x += self.direccion[0]
        self.rect.y += self.direccion[1]

        if self.rect.x > ancho-10: self.direccion[0] = -1
        if self.rect.x < 30      : self.direccion[0] = 1
        if self.rect.y < 30      : self.direccion[1] = 1
        if self.rect.y > largo-10: self.direccion[1] = -1
        c=len(pygame.sprite.spritecollide(self,g,False,None))
        if c >= 2:
            self.direccion[0] = self.direccion[0]*(-1)
            self.direccion[1] = self.direccion[1]*(-1)
        screen.blit(self.image,self.rect)

pygame.init;

screen = pygame.display.set_mode((ancho,largo))

pelota = Pelotas("ball.jpg")
elemento1 = Elementos("ball.jpg",0,150,[1,1])
elemento2 = Elementos("ball.jpg",150,0,[1,2])
elemento3 = Elementos("ball.jpg",300,120,[3,1])
elemento4 = Elementos("ball.jpg",400,65,[1,5])
elemento5 = Elementos("ball.jpg",470,65,[1,-95])
elemento6 = Elementos("ball.jpg",450,10,[-1,3])
elemento7 = Elementos("ball.jpg",400,65,[25,5])

g = pygame.sprite.Group()
ge=pygame.sprite.Group()
g.add([pelota,elemento1,elemento2,elemento3,elemento4,elemento5,elemento6,elemento7])
ge.add([elemento1,elemento2,elemento3,elemento4,elemento5,elemento6,elemento7])

while True:
    for e  in pygame.event.get():
        if e.type == pygame.KEYUP:
            if e.key == pygame.K_s: sys.exit(0)
    screen.fill((0,0,0))
    g.update()
    pygame.time.delay(10)
    pygame.display.flip()
